development:
  SERWER_ADDRESS_WITH_PROTOCOL: <%= ENV['CUSTOM_SERWER_ADDRESS_WITH_PROTOCOL'] %>
  SERWER_ADDRESS: <%= ENV['CUSTOM_SERWER_ADDRESS'] %>
  DEVISE_JWT_SECRET_KEY: <%= ENV['CUSTOM_DEVISE_JWT_SECRET_KEY'] %>
  REDIS_URL: <%= ENV['CUSTOM_REDIS_URL'] %>
  REDIS_DB_NR: <%= ENV['CUSTOM_REDIS_DB_NR'] %>
  SIDEKIQ_USERNAME: <%= ENV['CUSTOM_SIDEKIQ_USERNAME'] %>
  SIDEKIQ_PASSWORD: <%= ENV['CUSTOM_SIDEKIQ_PASSWORD'] %>
  SIDEKIQ_REDIS: <%= ENV['CUSTOM_SIDEKIQ_REDIS'] %>
