development:
  SERWER_ADDRESS_WITH_PROTOCOL: <%= ENV['CUSTOM_SERWER_ADDRESS_WITH_PROTOCOL'] %>
  SERWER_ADDRESS: <%= ENV['CUSTOM_SERWER_ADDRESS'] %>
  DEVISE_JWT_SECRET_KEY: <%= ENV['CUSTOM_DEVISE_JWT_SECRET_KEY'] %>
  REDIS_URL: <%= ENV['CUSTOM_REDIS_URL'] %>
  REDIS_DB_NR: <%= ENV['CUSTOM_REDIS_DB_NR'] %>
  SIDEKIQ_USERNAME: <%= ENV['CUSTOM_SIDEKIQ_USERNAME'] %>
  SIDEKIQ_PASSWORD: <%= ENV['CUSTOM_SIDEKIQ_PASSWORD'] %>
  SIDEKIQ_REDIS: <%= ENV['CUSTOM_SIDEKIQ_REDIS'] %>
  DEVISE_SECRET_KEY: "32b57b6f237cad3720bd5ab8fd67649587da0906279611b7f72e43bc92eda950be3ac3801e3c1ddb8b87ef5be20677db140c95c1000c5cdc2f8d973a7f6fba12"